import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: 342,
    marginLeft: 'auto',
    marginRight: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F1FA',
    borderRadius: 25,
  },
  headingContainer: {
    height: 56,
    paddingHorizontal: 10,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    flexDirection: 'row',
    width: 167,

    borderRadius: 25,
  },
  headingText: {
    height: 48,
    width: 167,
    fontSize: 18,
    color: 'black',
    fontFamily: 'Inter-Medium',
    textAlign: 'center',
    textAlignVertical: 'center',
    borderRadius: 25,
  },
  selectedText: {
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'Inter-Medium',
  },
  MainContainer: {
    height: '100%',
    backgroundColor: 'white',
  },
  headerContainer: {
    marginTop: 20,
    marginHorizontal: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterButton: {
    height: 40,
    width: 96,
    borderRadius: 40,
    borderColor: 'lightgrey',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  filterImage: {
    height: 24,
    width: 24,
  },
  filterButtonText: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: 'black',
  },
  burgerIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  filterImage2: {
    height: 40,
    width: 40,
    borderRadius: 10,
  },
  financialContainer: {
    marginVertical: 30,
    position: 'relative',
  },
  financialImage: {
    height: 196,
    width: 196,
    alignSelf: 'center',
  },
  financialText: {
    width: 147,
    height: 50,
    overflow: 'hidden',
    fontFamily: 'Inter-Bold',
    fontSize: 32,
    textAlign: 'center',
    marginTop: 30,
    color: 'black',
    alignSelf: 'center',
    marginBottom: 30,
    position: 'absolute',
    top: 45,
  },
  bottomContent: {},
  bottomContainer: {
    marginTop: 20,
    marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bottomContentButton: {
    height: 40,
    width: 115,
    borderRadius: 40,
    borderColor: 'lightgrey',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  bottomImage: {
    height: 20,
    width: 20,
    borderRadius: 10,
  },
  bottomButtonText: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: 'black',
  },
  buttomIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: 'lightgrey',
  },
  categorybtn: {height: 40, width: 40},
  category1: {backgroundColor: 'orange'},
  category2: {backgroundColor: '#7F3DFF'},
  category3: {backgroundColor: 'red'},
  amountColor1: {color: 'red'},
  BarGraphContainer: {
    paddingVertical: 20,
  },
  Incomecategory: {backgroundColor: '#00A86B'},
  IncomeCategory2: {backgroundColor: 'black'},
  IncomeAmountColor: {color: '#00A86B'},
});
